<?php
unset($_SESSION["errorJabatanKosong"]);
unset($_SESSION["errorPosisiJabatanKosong"]);
unset($_SESSION["errorPangkatKosong"]);
unset($_SESSION["errorUnitKerjaKosong"]);
unset($_SESSION["errorPosisiKadis1"]);
unset($_SESSION["errorPosisiKadis2"]);
unset($_SESSION["errorPosisiKabid1"]);
unset($_SESSION["errorPosisiKabid2"]);
unset($_SESSION["errorDuplikatJabatan"]);
unset($_SESSION["errorJabatanKabid"]);
unset($_SESSION["errorNip"]);
unset($_SESSION["errorNama"]);
unset($_SESSION["errorUsername"]);
unset($_SESSION["errorEmail1"]);
unset($_SESSION["errorEmail2"]);
unset($_SESSION["errorEditPass"]);
unset($_SESSION["errorEditPassLen"]);
unset($_SESSION["errorEditPassLama"]);
?>
